In [4]:
import numpy as np
QY=np.array([[16,11,10,16,24,40,51,61],
            [12,12,14,19,26,58,60,55],
            [14,13,16,24,40,57,69,56],
            [14,17,22,29,51,87,80,62],
            [18,22,37,56,68,109,103,77],
            [24,35,55,64,81,104,113,92],
            [49,64,78,87,103,121,120,101],
            [72,92,95,98,112,100,103,99]])

In [5]:
print(QY.T)

[[ 16  12  14  14  18  24  49  72]
 [ 11  12  13  17  22  35  64  92]
 [ 10  14  16  22  37  55  78  95]
 [ 16  19  24  29  56  64  87  98]
 [ 24  26  40  51  68  81 103 112]
 [ 40  58  57  87 109 104 121 100]
 [ 51  60  69  80 103 113 120 103]
 [ 61  55  56  62  77  92 101  99]]
